### ISSUE TITLE
❌ fix dependency graph permissions 

### ISSUE THREAD

**Issue by yacosta738** [dallay/lyra#33]
```yml
    - name: ⚙️ Setup Gradle 🐘
      uses: gradle/gradle-build-action@v2.11.1
      id: gradle
      with:
        arguments: ${{ inputs.gradle-arguments }}
        dependency-graph: generate-and-submit
```

Error

[Build and Test 🧪](https://github.com/yacosta738/lyra/actions/runs/7351308101/job/20014438409#step:19:10)
Failed to submit dependency graph dependency-graph-reports/deploy_to_main_stage_-build.json.
HttpError: Resource not accessible by integration
Please ensure that the 'contents: write' permission is available for the workflow job.
Note that this permission is never available for a 'pull_request' trigger from a repository fork.
![Screenshot 2023-12-28 at 22 22 06](https://github.com/yacosta738/lyra/assets/33158051/4c62d3eb-8fa4-4912-8f6a-971283eb775c)
